# -*- coding: utf-8 -*-
"""H.W.1.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/12DihzvISSBwth1HhzVXS97Gvnu70N3Od

# **Step1. 連結雲端的資料**
"""

from google.colab import drive
drive.mount('/content/gdrive/', force_remount=True)

import os
os.chdir("/content/gdrive/My Drive/")
!ls -l "/content/gdrive/My Drive/112-2LATIA/H.W.1/高雄市失業率.csv"
#!ls -l "自行填寫正確的路徑"

import pandas as pd
import matplotlib.pyplot as plt
import numpy as np
csv_file = "/content/gdrive/My Drive/112-2LATIA/H.W.1/高雄市失業率.csv"
#csv_file ="自行填寫正確的路徑"

"""# **Step2. 問題及回答**

**Q1. 高雄市男性及女性的失業率趨勢?**
"""

df = pd.read_csv(csv_file)

df['年別'] = pd.to_datetime(df['年別'].str[:-1], format='%Y')
df.set_index('年別', inplace=True)

# 繪製長條圖
plt.figure(figsize=(8, 6))

plt.plot(df.index, df['女性失業率'], color='indianred', label='Women')
plt.plot(df.index, df['男性失業率'], color='steelblue', label='Men')

plt.title('Kaohsiung City unemployment rate trend from 2013 to 2022', fontsize=16, weight='bold')
plt.xlabel('Years')
plt.ylabel('Unemployment rate(%)')

plt.legend()

plt.tight_layout()

plt.show()

"""**Q2. 高雄市失業率男女比的趨勢?**"""

df = pd.read_csv(csv_file)
df['年別'] = pd.to_datetime(df['年別'].str[:-1], format='%Y')
df.set_index('年別', inplace=True)

# 繪製長條圖
plt.figure(figsize=(8, 6))

plt.plot(df.index, df['男性失業率']/df['女性失業率'])
plt.title('Trends in the male-to-female ratio of unemployment rate in Kaohsiung City', fontsize=16, weight='bold')
plt.xlabel('Years')
plt.ylabel('Unemployment rate(%)')

plt.tight_layout()

plt.show()

"""**當男女比率大於1時表示男性失業率較高，反之為女性
可以看出只有在2020及2021年時的比率小於1，其餘皆大於1**

**Q3.2013-2022年高雄市男性不同教育程度的失業率?**
"""

years = ['2013', '2014', '2015', '2016', '2017', '2018', '2019', '2020', '2021', '2022']
edu_levels = ['Junior high school and below', 'High school vocational', 'College and above']
unemployment_rates = {
    'Junior high school and below (M)': df['男性失業率按教育程度別分國中及以下'],
    'High school vocational (M)': df['男性失業率按教育程度別分高中職'],
    'College and above (M)': df['男性失業率按教育程度別分大專及以上']
}

# 繪製長條圖
fig, ax = plt.subplots(figsize=(8, 6))
bar_width = 0.2
index = range(len(years))
colors = ['skyblue', 'steelblue', 'darkblue']

for i, (edu_level, rates) in enumerate(unemployment_rates.items()):
    ax.bar([x + i * bar_width for x in index], rates, bar_width, label=edu_level, color=colors[i])

ax.set_xlabel('Years')
ax.set_ylabel('Unemployment rate(%)')
ax.set_title('Unemployment rate of men with different educational levels in Kaohsiung City from 2013 to 2022', fontsize=16, weight='bold')
ax.set_xticks([x + bar_width for x in index])
ax.set_xticklabels(years)
ax.legend()

plt.tight_layout()
plt.show()

"""**Q4.2013-2022年高雄市女性不同教育程度的失業率?**"""

years = ['2013', '2014', '2015', '2016', '2017', '2018', '2019', '2020', '2021', '2022']
edu_levels = ['Junior high school and below', 'High school vocational', 'College and above']
unemployment_rates = {
    'Junior high school and below (W)': df['女性失業率按教育程度別分國中及以下'],
    'High school vocational (W)': df['女性失業率按教育程度別分高中職'],
    'College and above (W)': df['女性失業率按教育程度別分大專及以上']
}

# 繪製長條圖
fig, ax = plt.subplots(figsize=(8, 6))
bar_width = 0.2
index = range(len(years))
colors = ['lightcoral', 'indianred', 'brown']

for i, (edu_level, rates) in enumerate(unemployment_rates.items()):
    ax.bar([x + i * bar_width for x in index], rates, bar_width, label=edu_level, color=colors[i])

ax.set_xlabel('Years')
ax.set_ylabel('Unemployment rate(%)')
ax.set_title('Unemployment rate of men with different educational levels in Kaohsiung City from 2013 to 2022', fontsize=16, weight='bold')
ax.set_xticks([x + bar_width for x in index])
ax.set_xticklabels(years)
ax.legend()

plt.tight_layout()
plt.show()

"""可以看出女性的失業率與教育程度呈正相關，但男性的不一定

**Q5. 2013-2022年高雄市男性不同年齡的失業率?**
"""

years = ['2013', '2014', '2015', '2016', '2017', '2018', '2019', '2020', '2021', '2022']
edu_levels = ['15-24 (M)', '25-29 (M)', '30-34 (M)', '35-39 (M)', '40-44 (M)', '45-49 (M)', '50-54 (M)', '55-59 (M)', '60-64 (M)', '65up (M)']
unemployment_rates = {
    '15-24 (M)': df['男性失業率按年齡別分15到24歲'],
    '25-29 (M)': df['男性失業率按年齡別分25到29歲'],
    '30-34 (M)': df['男性失業率按年齡別分30到34歲'],
    '35-39 (M)': df['男性失業率按年齡別分35到39歲'],
    '40-44 (M)': df['男性失業率按年齡別分40到44歲'],
    '45-49 (M)': df['男性失業率按年齡別分45到49歲'],
    '50-54 (M)': df['男性失業率按年齡別分50到54歲'],
    '55-59 (M)': df['男性失業率按年齡別分55到59歲'],
    '60-64 (M)': df['男性失業率按年齡別分60到64歲'],
    '65up (M)': df['男性失業率按年齡別分65歲以上']
}

# 繪製堆疊長條圖
fig, ax = plt.subplots(figsize=(10, 6))

index = np.arange(len(years))
bar_width = 0.35

prev_rates = np.zeros(len(years))  # 用於跟踪堆疊的高度

for edu_level in edu_levels:
    rates = unemployment_rates[edu_level]
    ax.bar(index, rates, bar_width, bottom=prev_rates, label=edu_level)
    prev_rates += rates

ax.set_xlabel('Years', fontsize=16)
ax.set_ylabel('Unemployment rate(%)', fontsize=16)
ax.set_title('Stacked Unemployment rate of men with different educational levels in Kaohsiung City from 2013 to 2022', fontsize=16, weight='bold')
ax.set_xticks(index)
ax.set_xticklabels(years)
ax.legend(loc=[1.02, 0], title="Ages")

plt.tight_layout()
plt.show()

"""**Q6. 2013-2022年高雄市女性不同年齡的失業率?**"""

years = ['2013', '2014', '2015', '2016', '2017', '2018', '2019', '2020', '2021', '2022']
edu_levels = ['15-24 (W)', '25-29 (W)', '30-34 (W)', '35-39 (W)', '40-44 (W)', '45-49 (W)', '50-54 (W)', '55-59 (W)', '60-64 (W)', '65up (W)']
unemployment_rates = {
    '15-24 (W)': df['女性失業率按年齡別分15到24歲'],
    '25-29 (W)': df['女性失業率按年齡別分25到29歲'],
    '30-34 (W)': df['女性失業率按年齡別分30到34歲'],
    '35-39 (W)': df['女性失業率按年齡別分35到39歲'],
    '40-44 (W)': df['女性失業率按年齡別分40到44歲'],
    '45-49 (W)': df['女性失業率按年齡別分45到49歲'],
    '50-54 (W)': df['女性失業率按年齡別分50到54歲'],
    '55-59 (W)': df['女性失業率按年齡別分55到59歲'],
    '60-64 (W)': df['女性失業率按年齡別分60到64歲'],
    '65up (W)': df['女性失業率按年齡別分65歲以上']
}

# 繪製堆疊長條圖
fig, ax = plt.subplots(figsize=(10, 6))

index = np.arange(len(years))
bar_width = 0.35

prev_rates = np.zeros(len(years))  # 用於跟踪堆疊的高度

for edu_level in edu_levels:
    rates = unemployment_rates[edu_level]
    ax.bar(index, rates, bar_width, bottom=prev_rates, label=edu_level)
    prev_rates += rates

ax.set_xlabel('Years', fontsize=16)
ax.set_ylabel('Unemployment rate(%)', fontsize=16)
ax.set_title('Stacked Unemployment rate of men with different educational levels in Kaohsiung City from 2013 to 2022', fontsize=16, weight='bold')
ax.set_xticks(index)
ax.set_xticklabels(years)
ax.legend(loc=[1.02, 0], title="Ages")

plt.tight_layout()
plt.show()

"""其中年紀在15-24歲的年齡層失業率最高"""