# -*- coding: utf-8 -*-
"""Week3_20240305.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1jVR3P0uUzX8YpjIEFOcXI4vsxiTupaJg
"""

from google.colab import drive
drive.mount('/content/gdrive/', force_remount=True)

import os
os.chdir("/content/gdrive/My Drive/")
!ls -l "/content/gdrive/My Drive/112-2LATIA/Week2/112_student.csv"
#!ls -l "自行填寫正確的路徑"

import pandas as pd

csv_file = "/content/gdrive/My Drive/112-2LATIA/Week2/112_student.csv"

df = pd.read_csv(csv_file)

"""**1.哪間大專院校有最多的學士生**"""

df1 = df[['總計']] # 取出想要觀看的欄位
print("本資料集共有", df1, "筆紀錄")

df1_1 = df1[df['等級別'] == 'B 學士']
print("有招生學士學制的學校數量為", len(df1_1), "\n")

df1_1_sorted = df1_1.sort_values(by='總計', ascending=False)

max_school_index = df1_1_sorted.index[0]
max_school_name = df.loc[max_school_index, '學校名稱']

print("112學年度在籍的學士生最多人數之學校為", max_school_name)

"""2. **國立？所；私立？所**"""

type_list = [] # 建立空字串

for i in df['學校名稱']:
    if ('國立' in i) or ('市立' in i):
        type_list.append('公立')
    else:
        type_list.append('私立')

df['公私立'] = type_list # 將 Dataframe 新增「公私立」column

df2 = df.drop_duplicates(subset='學校代碼')
count = df2['公私立'].value_counts()

print(df2)
print(f"本資料集共收集了 {len(df2)} 所學校，其中公立：{count['公立']} 所；私立：{count['私立']} 所。")

"""3. **各等級別學制共有？所**"""

df3 = df.drop_duplicates(subset=['學校名稱', '等級別'])

counts = df3['等級別'].value_counts()

degree_list = list(df['等級別'].unique())

print(f"本資料集總共收集了 {len(set(df3['學校名稱']))} 所學校，各等級學制當中：")

for degree in degree_list:
    print(f"一共有{counts[degree]} 所學校， 有招收{degree}。")

"""**Week2提出的問題:師範體系的有幾人?**"""

type_list = [] # 建立空字串

for i in df['學校名稱']:
    if ('師範' in i):
        type_list.append('師範大學')
    else:
        type_list.append('普通大學')

df['師範體系'] = type_list # 將 Dataframe 新增「公私立」column

df4 = df.drop_duplicates(subset='學校代碼')
count = df4['師範體系'].value_counts()


print(f"本資料集共收集了 {len(df4)} 所學校，其中師範體系：{count['師範大學']} 所；非師範體系：{count['普通大學']} 所。")